name: .NET CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/dotnet.yml'
      - 'DOTNET-example/**'

jobs:
  build_and_run_dotnet_app:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    name: .NET ${{ matrix.dotnet-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up DOTNET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Run and Test the app
        run: |
          dotnet run --project DOTNET-example/Web-App &
          TEMP_OUTPUT_FILE=$(mktemp)
          WAIT_TIME=20
          for i in `seq 1 3`;
          do
            sleep ${WAIT_TIME};
            HTTP_CODE=$(curl --silent --output $TEMP_OUTPUT_FILE --write-out "%{http_code}" "http://localhost:5114")
            if [[ ${HTTP_CODE} -lt 200 || ${HTTP_CODE} -gt 299 ]] ; then
              >&2 cat $TEMP_OUTPUT_FILE
              WAIT_TIME=$((WAIT_TIME * $i));
            else
              cat $TEMP_OUTPUT_FILE
              rm $TEMP_OUTPUT_FILE
              break
            fi
          done
